version: '3.9'
services:
  chromadb:
    image: chromadb/chroma:0.5.5
    container_name: rag-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./.chroma_data:/chroma/chroma
    restart: unless-stopped

#  redis:
#    image: redis:7.2-alpine
#    container_name: rag-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./.redis_data:/data
#    # 强制开启 AOF 持久化，这样才会真正把聊天记忆写入到映射的 /data 目录中！
#    command: redis-server --appendonly yes
#    restart: unless-stopped